image: node:18.17.0

build:
    script:
        - npm install 
        - npm run build
        - apt-get update -y
        - apt-get install -y rsync
        - apt-get install -y openssh-client
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        - rsync -av --delete -e "ssh -o StrictHostKeyChecking=no" ./dist/ ubuntu@$SERVER_IP:/var/www/html/
